//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  accueil_categories: Accueil_Categories;
  accueil_categoriesConnection: Accueil_CategoriesConnection;
  realisations: Realisations;
  realisationsConnection: RealisationsConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAccueil_CategoriesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAccueil_CategoriesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Accueil_CategoriesFilter>;
};


export type QueryRealisationsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryRealisationsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<RealisationsFilter>;
};

export type DocumentFilter = {
  accueil_categories?: InputMaybe<Accueil_CategoriesFilter>;
  realisations?: InputMaybe<RealisationsFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Accueil_Categories | Realisations | Folder;

export type Accueil_Categories = Node & Document & {
  __typename?: 'Accueil_categories';
  image: Scalars['String']['output'];
  title: Scalars['String']['output'];
  description: Scalars['JSON']['output'];
  tag: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Accueil_CategoriesFilter = {
  image?: InputMaybe<ImageFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<RichTextFilter>;
  tag?: InputMaybe<StringFilter>;
};

export type Accueil_CategoriesConnectionEdges = {
  __typename?: 'Accueil_categoriesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Accueil_Categories>;
};

export type Accueil_CategoriesConnection = Connection & {
  __typename?: 'Accueil_categoriesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Accueil_CategoriesConnectionEdges>>>;
};

export type Realisations = Node & Document & {
  __typename?: 'Realisations';
  title: Scalars['String']['output'];
  image: Scalars['String']['output'];
  accroche?: Maybe<Scalars['String']['output']>;
  location?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['JSON']['output']>;
  gallery?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  publishDate?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RealisationsFilter = {
  title?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  accroche?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  description?: InputMaybe<RichTextFilter>;
  gallery?: InputMaybe<ImageFilter>;
  tags?: InputMaybe<StringFilter>;
  publishDate?: InputMaybe<DatetimeFilter>;
};

export type RealisationsConnectionEdges = {
  __typename?: 'RealisationsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Realisations>;
};

export type RealisationsConnection = Connection & {
  __typename?: 'RealisationsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<RealisationsConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateAccueil_categories: Accueil_Categories;
  createAccueil_categories: Accueil_Categories;
  updateRealisations: Realisations;
  createRealisations: Realisations;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateAccueil_CategoriesArgs = {
  relativePath: Scalars['String']['input'];
  params: Accueil_CategoriesMutation;
};


export type MutationCreateAccueil_CategoriesArgs = {
  relativePath: Scalars['String']['input'];
  params: Accueil_CategoriesMutation;
};


export type MutationUpdateRealisationsArgs = {
  relativePath: Scalars['String']['input'];
  params: RealisationsMutation;
};


export type MutationCreateRealisationsArgs = {
  relativePath: Scalars['String']['input'];
  params: RealisationsMutation;
};

export type DocumentUpdateMutation = {
  accueil_categories?: InputMaybe<Accueil_CategoriesMutation>;
  realisations?: InputMaybe<RealisationsMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  accueil_categories?: InputMaybe<Accueil_CategoriesMutation>;
  realisations?: InputMaybe<RealisationsMutation>;
};

export type Accueil_CategoriesMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['JSON']['input']>;
  tag?: InputMaybe<Scalars['String']['input']>;
};

export type RealisationsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  accroche?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['JSON']['input']>;
  gallery?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  publishDate?: InputMaybe<Scalars['String']['input']>;
};

export type Accueil_CategoriesPartsFragment = { __typename: 'Accueil_categories', image: string, title: string, description: any, tag: string };

export type RealisationsPartsFragment = { __typename: 'Realisations', title: string, image: string, accroche?: string | null, location?: string | null, description?: any | null, gallery?: Array<string | null> | null, tags?: Array<string | null> | null, publishDate?: string | null };

export type Accueil_CategoriesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type Accueil_CategoriesQuery = { __typename?: 'Query', accueil_categories: { __typename: 'Accueil_categories', id: string, image: string, title: string, description: any, tag: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type Accueil_CategoriesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Accueil_CategoriesFilter>;
}>;


export type Accueil_CategoriesConnectionQuery = { __typename?: 'Query', accueil_categoriesConnection: { __typename?: 'Accueil_categoriesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'Accueil_categoriesConnectionEdges', cursor: string, node?: { __typename: 'Accueil_categories', id: string, image: string, title: string, description: any, tag: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type RealisationsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type RealisationsQuery = { __typename?: 'Query', realisations: { __typename: 'Realisations', id: string, title: string, image: string, accroche?: string | null, location?: string | null, description?: any | null, gallery?: Array<string | null> | null, tags?: Array<string | null> | null, publishDate?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type RealisationsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<RealisationsFilter>;
}>;


export type RealisationsConnectionQuery = { __typename?: 'Query', realisationsConnection: { __typename?: 'RealisationsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'RealisationsConnectionEdges', cursor: string, node?: { __typename: 'Realisations', id: string, title: string, image: string, accroche?: string | null, location?: string | null, description?: any | null, gallery?: Array<string | null> | null, tags?: Array<string | null> | null, publishDate?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const Accueil_CategoriesPartsFragmentDoc = gql`
    fragment Accueil_categoriesParts on Accueil_categories {
  __typename
  image
  title
  description
  tag
}
    `;
export const RealisationsPartsFragmentDoc = gql`
    fragment RealisationsParts on Realisations {
  __typename
  title
  image
  accroche
  location
  description
  gallery
  tags
  publishDate
}
    `;
export const Accueil_CategoriesDocument = gql`
    query accueil_categories($relativePath: String!) {
  accueil_categories(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Accueil_categoriesParts
  }
}
    ${Accueil_CategoriesPartsFragmentDoc}`;
export const Accueil_CategoriesConnectionDocument = gql`
    query accueil_categoriesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Accueil_categoriesFilter) {
  accueil_categoriesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Accueil_categoriesParts
      }
    }
  }
}
    ${Accueil_CategoriesPartsFragmentDoc}`;
export const RealisationsDocument = gql`
    query realisations($relativePath: String!) {
  realisations(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...RealisationsParts
  }
}
    ${RealisationsPartsFragmentDoc}`;
export const RealisationsConnectionDocument = gql`
    query realisationsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: RealisationsFilter) {
  realisationsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...RealisationsParts
      }
    }
  }
}
    ${RealisationsPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      accueil_categories(variables: Accueil_CategoriesQueryVariables, options?: C): Promise<{data: Accueil_CategoriesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Accueil_CategoriesQueryVariables, query: string}> {
        return requester<{data: Accueil_CategoriesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Accueil_CategoriesQueryVariables, query: string}, Accueil_CategoriesQueryVariables>(Accueil_CategoriesDocument, variables, options);
      },
    accueil_categoriesConnection(variables?: Accueil_CategoriesConnectionQueryVariables, options?: C): Promise<{data: Accueil_CategoriesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Accueil_CategoriesConnectionQueryVariables, query: string}> {
        return requester<{data: Accueil_CategoriesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Accueil_CategoriesConnectionQueryVariables, query: string}, Accueil_CategoriesConnectionQueryVariables>(Accueil_CategoriesConnectionDocument, variables, options);
      },
    realisations(variables: RealisationsQueryVariables, options?: C): Promise<{data: RealisationsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RealisationsQueryVariables, query: string}> {
        return requester<{data: RealisationsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RealisationsQueryVariables, query: string}, RealisationsQueryVariables>(RealisationsDocument, variables, options);
      },
    realisationsConnection(variables?: RealisationsConnectionQueryVariables, options?: C): Promise<{data: RealisationsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RealisationsConnectionQueryVariables, query: string}> {
        return requester<{data: RealisationsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RealisationsConnectionQueryVariables, query: string}, RealisationsConnectionQueryVariables>(RealisationsConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  